sudo: false
language: node_js
node_js:
  - '15'
matrix:
  include:
    - dist: bionic
    - dist: xenial
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm run coveralls
